disable_all_formatting = true
indent_style = "Visual"
max_width = 120
tab_spaces = 2
space_before_colon = true
spaces_within_parens_and_brackets = true
remove_blank_lines_at_start_or_end_of_block = false
# force_multiline_blocks = true
fn_args_density = "Vertical"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
blank_lines_lower_bound = 1
report_todo = "Always"
report_fixme = "Always"
# license_template_path = ""