language: rust
matrix:
  include:
  - rust: stable
  - rust: beta
  - rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
  - cargo coveralls
branches:
  only:
  - master
  - develop