pub const FUNCTION_CODE_READ_COILS: u8 = 0x01;
pub const FUNCTION_CODE_READ_DISCRETE_INPUTS: u8 = 0x02;
pub const FUNCTION_CODE_READ_HOLDING_REGISTERS: u8 = 0x03;
pub const FUNCTION_CODE_READ_INPUT_REGISTERS: u8 = 0x04;
pub const FUNCTION_CODE_WRITE_MULTIPLE_COILS: u8 = 0x0F;
pub const FUNCTION_CODE_WRITE_MULTIPLE_REGISTERS: u8 = 0x10;
pub const FUNCTION_CODE_WRITE_SINGLE_COIL: u8 = 0x05;
pub const FUNCTION_CODE_WRITE_SINGLE_REGISTER: u8 = 0x06;

pub const MODBUS_DEFAULT_UNIT_IDENTIFIER: u8 = 0x01;
pub const MODBUS_FUNCTION_CODE_LENGTH: u16 = 0x0001;
pub const MODBUS_HEADER_SIZE: u8 = 0x07;
pub const MODBUS_PROTOCOL_IDENTIFIER_TCP: u16 = 0x0000;
pub const MODBUS_TCP_PORT: u16 = 502;
pub const MODBUS_TRANSACTION_ID_INITIALIZER: u16 = 0x0001;
pub const MODBUS_UNIT_IDENTIFIER_LENGTH: u16 = 0x0001;

pub const MODBUS_READ_COIL_MINIMUM_PAYLOAD_LENGTH: usize = 2;
pub const MODBUS_READ_REGISTER_MINIMUM_PAYLOAD_LENGTH: usize = 3;
pub const MODBUS_WRITE_MINIMUM_PAYLOAD_LENGTH: usize = 4;
